-- Generated by tools/import_animated_sprites.py --set gen4.
-- Pokemon Diamond/Pearl animated fronts, National Dex #001-#151.
return {
  BULBASAUR = {
    front = { image = "assets/battle/front-animated/gen4/bulbasaur.png", width = 86, height = 86, columns = 16, frames = 37, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  IVYSAUR = {
    front = { image = "assets/battle/front-animated/gen4/ivysaur.png", width = 80, height = 80, columns = 16, frames = 34, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VENUSAUR = {
    front = { image = "assets/battle/front-animated/gen4/venusaur.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CHARMANDER = {
    front = { image = "assets/battle/front-animated/gen4/charmander.png", width = 80, height = 80, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CHARMELEON = {
    front = { image = "assets/battle/front-animated/gen4/charmeleon.png", width = 80, height = 80, columns = 16, frames = 22, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CHARIZARD = {
    front = { image = "assets/battle/front-animated/gen4/charizard.png", width = 84, height = 84, columns = 16, frames = 36, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SQUIRTLE = {
    front = { image = "assets/battle/front-animated/gen4/squirtle.png", width = 80, height = 80, columns = 16, frames = 58, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  WARTORTLE = {
    front = { image = "assets/battle/front-animated/gen4/wartortle.png", width = 110, height = 110, columns = 16, frames = 36, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  BLASTOISE = {
    front = { image = "assets/battle/front-animated/gen4/blastoise.png", width = 80, height = 80, columns = 16, frames = 37, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CATERPIE = {
    front = { image = "assets/battle/front-animated/gen4/caterpie.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  METAPOD = {
    front = { image = "assets/battle/front-animated/gen4/metapod.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  BUTTERFREE = {
    front = { image = "assets/battle/front-animated/gen4/butterfree.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  WEEDLE = {
    front = { image = "assets/battle/front-animated/gen4/weedle.png", width = 80, height = 80, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KAKUNA = {
    front = { image = "assets/battle/front-animated/gen4/kakuna.png", width = 80, height = 80, columns = 16, frames = 37, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  BEEDRILL = {
    front = { image = "assets/battle/front-animated/gen4/beedrill.png", width = 86, height = 86, columns = 16, frames = 29, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PIDGEY = {
    front = { image = "assets/battle/front-animated/gen4/pidgey.png", width = 80, height = 80, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PIDGEOTTO = {
    front = { image = "assets/battle/front-animated/gen4/pidgeotto.png", width = 92, height = 92, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PIDGEOT = {
    front = { image = "assets/battle/front-animated/gen4/pidgeot.png", width = 96, height = 96, columns = 16, frames = 22, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  RATTATA = {
    front = { image = "assets/battle/front-animated/gen4/rattata.png", width = 80, height = 80, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  RATICATE = {
    front = { image = "assets/battle/front-animated/gen4/raticate.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SPEAROW = {
    front = { image = "assets/battle/front-animated/gen4/spearow.png", width = 80, height = 80, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  FEAROW = {
    front = { image = "assets/battle/front-animated/gen4/fearow.png", width = 90, height = 90, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  EKANS = {
    front = { image = "assets/battle/front-animated/gen4/ekans.png", width = 100, height = 100, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ARBOK = {
    front = { image = "assets/battle/front-animated/gen4/arbok.png", width = 98, height = 98, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PIKACHU = {
    front = { image = "assets/battle/front-animated/gen4/pikachu.png", width = 80, height = 80, columns = 16, frames = 49, durations = {50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,2000} },
  },
  RAICHU = {
    front = { image = "assets/battle/front-animated/gen4/raichu.png", width = 80, height = 80, columns = 16, frames = 48, durations = {16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,2550} },
  },
  SANDSHREW = {
    front = { image = "assets/battle/front-animated/gen4/sandshrew.png", width = 124, height = 124, columns = 16, frames = 37, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SANDSLASH = {
    front = { image = "assets/battle/front-animated/gen4/sandslash.png", width = 80, height = 80, columns = 16, frames = 40, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NIDORAN_F = {
    front = { image = "assets/battle/front-animated/gen4/nidoran-f.png", width = 80, height = 80, columns = 16, frames = 22, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NIDORINA = {
    front = { image = "assets/battle/front-animated/gen4/nidorina.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NIDOQUEEN = {
    front = { image = "assets/battle/front-animated/gen4/nidoqueen.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NIDORAN_M = {
    front = { image = "assets/battle/front-animated/gen4/nidoran-m.png", width = 80, height = 80, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NIDORINO = {
    front = { image = "assets/battle/front-animated/gen4/nidorino.png", width = 80, height = 80, columns = 16, frames = 38, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NIDOKING = {
    front = { image = "assets/battle/front-animated/gen4/nidoking.png", width = 80, height = 80, columns = 16, frames = 38, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CLEFAIRY = {
    front = { image = "assets/battle/front-animated/gen4/clefairy.png", width = 80, height = 80, columns = 16, frames = 51, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CLEFABLE = {
    front = { image = "assets/battle/front-animated/gen4/clefable.png", width = 104, height = 104, columns = 16, frames = 35, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VULPIX = {
    front = { image = "assets/battle/front-animated/gen4/vulpix.png", width = 80, height = 80, columns = 16, frames = 28, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  NINETALES = {
    front = { image = "assets/battle/front-animated/gen4/ninetales.png", width = 84, height = 84, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  JIGGLYPUFF = {
    front = { image = "assets/battle/front-animated/gen4/jigglypuff.png", width = 80, height = 80, columns = 16, frames = 53, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  WIGGLYTUFF = {
    front = { image = "assets/battle/front-animated/gen4/wigglytuff.png", width = 106, height = 106, columns = 16, frames = 35, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ZUBAT = {
    front = { image = "assets/battle/front-animated/gen4/zubat.png", width = 80, height = 80, columns = 16, frames = 21, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GOLBAT = {
    front = { image = "assets/battle/front-animated/gen4/golbat.png", width = 86, height = 86, columns = 16, frames = 49, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ODDISH = {
    front = { image = "assets/battle/front-animated/gen4/oddish.png", width = 80, height = 80, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GLOOM = {
    front = { image = "assets/battle/front-animated/gen4/gloom.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VILEPLUME = {
    front = { image = "assets/battle/front-animated/gen4/vileplume.png", width = 90, height = 90, columns = 16, frames = 42, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PARAS = {
    front = { image = "assets/battle/front-animated/gen4/paras.png", width = 80, height = 80, columns = 16, frames = 33, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PARASECT = {
    front = { image = "assets/battle/front-animated/gen4/parasect.png", width = 90, height = 90, columns = 16, frames = 40, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VENONAT = {
    front = { image = "assets/battle/front-animated/gen4/venonat.png", width = 80, height = 80, columns = 16, frames = 77, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VENOMOTH = {
    front = { image = "assets/battle/front-animated/gen4/venomoth.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DIGLETT = {
    front = { image = "assets/battle/front-animated/gen4/diglett.png", width = 80, height = 80, columns = 16, frames = 34, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DUGTRIO = {
    front = { image = "assets/battle/front-animated/gen4/dugtrio.png", width = 80, height = 80, columns = 16, frames = 32, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MEOWTH = {
    front = { image = "assets/battle/front-animated/gen4/meowth.png", width = 80, height = 80, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PERSIAN = {
    front = { image = "assets/battle/front-animated/gen4/persian.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PSYDUCK = {
    front = { image = "assets/battle/front-animated/gen4/psyduck.png", width = 80, height = 80, columns = 16, frames = 51, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GOLDUCK = {
    front = { image = "assets/battle/front-animated/gen4/golduck.png", width = 90, height = 90, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MANKEY = {
    front = { image = "assets/battle/front-animated/gen4/mankey.png", width = 84, height = 84, columns = 16, frames = 31, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PRIMEAPE = {
    front = { image = "assets/battle/front-animated/gen4/primeape.png", width = 84, height = 84, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GROWLITHE = {
    front = { image = "assets/battle/front-animated/gen4/growlithe.png", width = 80, height = 80, columns = 16, frames = 58, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ARCANINE = {
    front = { image = "assets/battle/front-animated/gen4/arcanine.png", width = 80, height = 80, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  POLIWAG = {
    front = { image = "assets/battle/front-animated/gen4/poliwag.png", width = 80, height = 80, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  POLIWHIRL = {
    front = { image = "assets/battle/front-animated/gen4/poliwhirl.png", width = 80, height = 80, columns = 16, frames = 37, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  POLIWRATH = {
    front = { image = "assets/battle/front-animated/gen4/poliwrath.png", width = 80, height = 80, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ABRA = {
    front = { image = "assets/battle/front-animated/gen4/abra.png", width = 80, height = 80, columns = 16, frames = 32, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KADABRA = {
    front = { image = "assets/battle/front-animated/gen4/kadabra.png", width = 94, height = 94, columns = 16, frames = 44, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ALAKAZAM = {
    front = { image = "assets/battle/front-animated/gen4/alakazam.png", width = 90, height = 90, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MACHOP = {
    front = { image = "assets/battle/front-animated/gen4/machop.png", width = 80, height = 80, columns = 16, frames = 32, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MACHOKE = {
    front = { image = "assets/battle/front-animated/gen4/machoke.png", width = 84, height = 84, columns = 16, frames = 39, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MACHAMP = {
    front = { image = "assets/battle/front-animated/gen4/machamp.png", width = 88, height = 88, columns = 16, frames = 61, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  BELLSPROUT = {
    front = { image = "assets/battle/front-animated/gen4/bellsprout.png", width = 80, height = 80, columns = 16, frames = 31, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  WEEPINBELL = {
    front = { image = "assets/battle/front-animated/gen4/weepinbell.png", width = 80, height = 80, columns = 16, frames = 52, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VICTREEBEL = {
    front = { image = "assets/battle/front-animated/gen4/victreebel.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  TENTACOOL = {
    front = { image = "assets/battle/front-animated/gen4/tentacool.png", width = 90, height = 90, columns = 16, frames = 55, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  TENTACRUEL = {
    front = { image = "assets/battle/front-animated/gen4/tentacruel.png", width = 84, height = 84, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GEODUDE = {
    front = { image = "assets/battle/front-animated/gen4/geodude.png", width = 80, height = 80, columns = 16, frames = 49, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GRAVELER = {
    front = { image = "assets/battle/front-animated/gen4/graveler.png", width = 80, height = 80, columns = 16, frames = 33, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GOLEM = {
    front = { image = "assets/battle/front-animated/gen4/golem.png", width = 80, height = 80, columns = 16, frames = 45, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PONYTA = {
    front = { image = "assets/battle/front-animated/gen4/ponyta.png", width = 80, height = 80, columns = 16, frames = 39, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  RAPIDASH = {
    front = { image = "assets/battle/front-animated/gen4/rapidash.png", width = 104, height = 104, columns = 16, frames = 22, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SLOWPOKE = {
    front = { image = "assets/battle/front-animated/gen4/slowpoke.png", width = 90, height = 90, columns = 16, frames = 37, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SLOWBRO = {
    front = { image = "assets/battle/front-animated/gen4/slowbro.png", width = 90, height = 90, columns = 16, frames = 52, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MAGNEMITE = {
    front = { image = "assets/battle/front-animated/gen4/magnemite.png", width = 80, height = 80, columns = 16, frames = 21, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MAGNETON = {
    front = { image = "assets/battle/front-animated/gen4/magneton.png", width = 80, height = 80, columns = 16, frames = 64, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  FARFETCHD = {
    front = { image = "assets/battle/front-animated/gen4/farfetchd.png", width = 80, height = 80, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DODUO = {
    front = { image = "assets/battle/front-animated/gen4/doduo.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DODRIO = {
    front = { image = "assets/battle/front-animated/gen4/dodrio.png", width = 80, height = 80, columns = 16, frames = 21, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SEEL = {
    front = { image = "assets/battle/front-animated/gen4/seel.png", width = 112, height = 112, columns = 16, frames = 36, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DEWGONG = {
    front = { image = "assets/battle/front-animated/gen4/dewgong.png", width = 102, height = 102, columns = 16, frames = 31, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GRIMER = {
    front = { image = "assets/battle/front-animated/gen4/grimer.png", width = 84, height = 84, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MUK = {
    front = { image = "assets/battle/front-animated/gen4/muk.png", width = 104, height = 104, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SHELLDER = {
    front = { image = "assets/battle/front-animated/gen4/shellder.png", width = 80, height = 80, columns = 16, frames = 52, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CLOYSTER = {
    front = { image = "assets/battle/front-animated/gen4/cloyster.png", width = 98, height = 98, columns = 16, frames = 55, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GASTLY = {
    front = { image = "assets/battle/front-animated/gen4/gastly.png", width = 80, height = 80, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  HAUNTER = {
    front = { image = "assets/battle/front-animated/gen4/haunter.png", width = 86, height = 86, columns = 16, frames = 30, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GENGAR = {
    front = { image = "assets/battle/front-animated/gen4/gengar.png", width = 80, height = 80, columns = 16, frames = 29, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ONIX = {
    front = { image = "assets/battle/front-animated/gen4/onix.png", width = 94, height = 94, columns = 16, frames = 28, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DROWZEE = {
    front = { image = "assets/battle/front-animated/gen4/drowzee.png", width = 80, height = 80, columns = 16, frames = 43, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  HYPNO = {
    front = { image = "assets/battle/front-animated/gen4/hypno.png", width = 80, height = 80, columns = 16, frames = 48, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KRABBY = {
    front = { image = "assets/battle/front-animated/gen4/krabby.png", width = 80, height = 80, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KINGLER = {
    front = { image = "assets/battle/front-animated/gen4/kingler.png", width = 84, height = 84, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VOLTORB = {
    front = { image = "assets/battle/front-animated/gen4/voltorb.png", width = 80, height = 80, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ELECTRODE = {
    front = { image = "assets/battle/front-animated/gen4/electrode.png", width = 80, height = 80, columns = 16, frames = 42, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  EXEGGCUTE = {
    front = { image = "assets/battle/front-animated/gen4/exeggcute.png", width = 80, height = 80, columns = 16, frames = 48, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  EXEGGUTOR = {
    front = { image = "assets/battle/front-animated/gen4/exeggutor.png", width = 126, height = 126, columns = 16, frames = 36, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CUBONE = {
    front = { image = "assets/battle/front-animated/gen4/cubone.png", width = 80, height = 80, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MAROWAK = {
    front = { image = "assets/battle/front-animated/gen4/marowak.png", width = 80, height = 80, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  HITMONLEE = {
    front = { image = "assets/battle/front-animated/gen4/hitmonlee.png", width = 98, height = 98, columns = 16, frames = 36, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  HITMONCHAN = {
    front = { image = "assets/battle/front-animated/gen4/hitmonchan.png", width = 80, height = 80, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  LICKITUNG = {
    front = { image = "assets/battle/front-animated/gen4/lickitung.png", width = 88, height = 88, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KOFFING = {
    front = { image = "assets/battle/front-animated/gen4/koffing.png", width = 84, height = 84, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  WEEZING = {
    front = { image = "assets/battle/front-animated/gen4/weezing.png", width = 88, height = 88, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  RHYHORN = {
    front = { image = "assets/battle/front-animated/gen4/rhyhorn.png", width = 80, height = 80, columns = 16, frames = 31, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  RHYDON = {
    front = { image = "assets/battle/front-animated/gen4/rhydon.png", width = 86, height = 86, columns = 16, frames = 36, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  CHANSEY = {
    front = { image = "assets/battle/front-animated/gen4/chansey.png", width = 80, height = 80, columns = 16, frames = 93, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  TANGELA = {
    front = { image = "assets/battle/front-animated/gen4/tangela.png", width = 80, height = 80, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KANGASKHAN = {
    front = { image = "assets/battle/front-animated/gen4/kangaskhan.png", width = 100, height = 100, columns = 16, frames = 26, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  HORSEA = {
    front = { image = "assets/battle/front-animated/gen4/horsea.png", width = 80, height = 80, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SEADRA = {
    front = { image = "assets/battle/front-animated/gen4/seadra.png", width = 80, height = 80, columns = 16, frames = 53, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GOLDEEN = {
    front = { image = "assets/battle/front-animated/gen4/goldeen.png", width = 80, height = 80, columns = 16, frames = 51, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SEAKING = {
    front = { image = "assets/battle/front-animated/gen4/seaking.png", width = 80, height = 80, columns = 16, frames = 51, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  STARYU = {
    front = { image = "assets/battle/front-animated/gen4/staryu.png", width = 80, height = 80, columns = 16, frames = 52, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  STARMIE = {
    front = { image = "assets/battle/front-animated/gen4/starmie.png", width = 80, height = 80, columns = 16, frames = 52, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MR_MIME = {
    front = { image = "assets/battle/front-animated/gen4/mr-mime.png", width = 80, height = 80, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SCYTHER = {
    front = { image = "assets/battle/front-animated/gen4/scyther.png", width = 86, height = 86, columns = 16, frames = 40, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  JYNX = {
    front = { image = "assets/battle/front-animated/gen4/jynx.png", width = 80, height = 80, columns = 16, frames = 35, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ELECTABUZZ = {
    front = { image = "assets/battle/front-animated/gen4/electabuzz.png", width = 80, height = 80, columns = 16, frames = 55, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MAGMAR = {
    front = { image = "assets/battle/front-animated/gen4/magmar.png", width = 80, height = 80, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PINSIR = {
    front = { image = "assets/battle/front-animated/gen4/pinsir.png", width = 80, height = 80, columns = 16, frames = 25, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  TAUROS = {
    front = { image = "assets/battle/front-animated/gen4/tauros.png", width = 80, height = 80, columns = 16, frames = 45, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MAGIKARP = {
    front = { image = "assets/battle/front-animated/gen4/magikarp.png", width = 82, height = 82, columns = 16, frames = 42, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  GYARADOS = {
    front = { image = "assets/battle/front-animated/gen4/gyarados.png", width = 96, height = 96, columns = 16, frames = 22, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  LAPRAS = {
    front = { image = "assets/battle/front-animated/gen4/lapras.png", width = 92, height = 92, columns = 16, frames = 23, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DITTO = {
    front = { image = "assets/battle/front-animated/gen4/ditto.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  EEVEE = {
    front = { image = "assets/battle/front-animated/gen4/eevee.png", width = 80, height = 80, columns = 16, frames = 31, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  VAPOREON = {
    front = { image = "assets/battle/front-animated/gen4/vaporeon.png", width = 106, height = 106, columns = 16, frames = 42, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  JOLTEON = {
    front = { image = "assets/battle/front-animated/gen4/jolteon.png", width = 80, height = 80, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  FLAREON = {
    front = { image = "assets/battle/front-animated/gen4/flareon.png", width = 80, height = 80, columns = 16, frames = 30, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  PORYGON = {
    front = { image = "assets/battle/front-animated/gen4/porygon.png", width = 80, height = 80, columns = 16, frames = 28, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  OMANYTE = {
    front = { image = "assets/battle/front-animated/gen4/omanyte.png", width = 80, height = 80, columns = 16, frames = 53, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  OMASTAR = {
    front = { image = "assets/battle/front-animated/gen4/omastar.png", width = 80, height = 80, columns = 16, frames = 33, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KABUTO = {
    front = { image = "assets/battle/front-animated/gen4/kabuto.png", width = 80, height = 80, columns = 16, frames = 52, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  KABUTOPS = {
    front = { image = "assets/battle/front-animated/gen4/kabutops.png", width = 80, height = 80, columns = 16, frames = 28, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  AERODACTYL = {
    front = { image = "assets/battle/front-animated/gen4/aerodactyl.png", width = 88, height = 88, columns = 16, frames = 22, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  SNORLAX = {
    front = { image = "assets/battle/front-animated/gen4/snorlax.png", width = 80, height = 80, columns = 16, frames = 27, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ARTICUNO = {
    front = { image = "assets/battle/front-animated/gen4/articuno.png", width = 80, height = 80, columns = 16, frames = 47, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  ZAPDOS = {
    front = { image = "assets/battle/front-animated/gen4/zapdos.png", width = 84, height = 84, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MOLTRES = {
    front = { image = "assets/battle/front-animated/gen4/moltres.png", width = 102, height = 102, columns = 16, frames = 53, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DRATINI = {
    front = { image = "assets/battle/front-animated/gen4/dratini.png", width = 80, height = 80, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DRAGONAIR = {
    front = { image = "assets/battle/front-animated/gen4/dragonair.png", width = 86, height = 86, columns = 16, frames = 24, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  DRAGONITE = {
    front = { image = "assets/battle/front-animated/gen4/dragonite.png", width = 86, height = 86, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MEWTWO = {
    front = { image = "assets/battle/front-animated/gen4/mewtwo.png", width = 90, height = 90, columns = 16, frames = 41, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
  MEW = {
    front = { image = "assets/battle/front-animated/gen4/mew.png", width = 102, height = 102, columns = 16, frames = 54, durations = {30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,3000} },
  },
}
