-- Generated by tools/import_emerald_back_sprites.py.
-- Pokemon Emerald animated backs, National Dex #001-#151.
return {
  BULBASAUR = {
    back = { image = "assets/battle/back-animated/gen3/bulbasaur.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  IVYSAUR = {
    back = { image = "assets/battle/back-animated/gen3/ivysaur.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  VENUSAUR = {
    back = { image = "assets/battle/back-animated/gen3/venusaur.png", width = 69, height = 69, columns = 16, frames = 38, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  CHARMANDER = {
    back = { image = "assets/battle/back-animated/gen3/charmander.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  CHARMELEON = {
    back = { image = "assets/battle/back-animated/gen3/charmeleon.png", width = 66, height = 66, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  CHARIZARD = {
    back = { image = "assets/battle/back-animated/gen3/charizard.png", width = 75, height = 75, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  SQUIRTLE = {
    back = { image = "assets/battle/back-animated/gen3/squirtle.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  WARTORTLE = {
    back = { image = "assets/battle/back-animated/gen3/wartortle.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  BLASTOISE = {
    back = { image = "assets/battle/back-animated/gen3/blastoise.png", width = 75, height = 75, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  CATERPIE = {
    back = { image = "assets/battle/back-animated/gen3/caterpie.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  METAPOD = {
    back = { image = "assets/battle/back-animated/gen3/metapod.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  BUTTERFREE = {
    back = { image = "assets/battle/back-animated/gen3/butterfree.png", width = 89, height = 89, columns = 16, frames = 73, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  WEEDLE = {
    back = { image = "assets/battle/back-animated/gen3/weedle.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  KAKUNA = {
    back = { image = "assets/battle/back-animated/gen3/kakuna.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  BEEDRILL = {
    back = { image = "assets/battle/back-animated/gen3/beedrill.png", width = 80, height = 80, columns = 16, frames = 39, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1067}, stableAnchor = true },
  },
  PIDGEY = {
    back = { image = "assets/battle/back-animated/gen3/pidgey.png", width = 72, height = 72, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  PIDGEOTTO = {
    back = { image = "assets/battle/back-animated/gen3/pidgeotto.png", width = 74, height = 74, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  PIDGEOT = {
    back = { image = "assets/battle/back-animated/gen3/pidgeot.png", width = 76, height = 76, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  RATTATA = {
    back = { image = "assets/battle/back-animated/gen3/rattata.png", width = 79, height = 79, columns = 16, frames = 43, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  RATICATE = {
    back = { image = "assets/battle/back-animated/gen3/raticate.png", width = 86, height = 86, columns = 16, frames = 43, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  SPEAROW = {
    back = { image = "assets/battle/back-animated/gen3/spearow.png", width = 67, height = 67, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  FEAROW = {
    back = { image = "assets/battle/back-animated/gen3/fearow.png", width = 82, height = 82, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  EKANS = {
    back = { image = "assets/battle/back-animated/gen3/ekans.png", width = 71, height = 71, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  ARBOK = {
    back = { image = "assets/battle/back-animated/gen3/arbok.png", width = 66, height = 66, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  PIKACHU = {
    back = { image = "assets/battle/back-animated/gen3/pikachu.png", width = 64, height = 64, columns = 16, frames = 30, durations = {50,50,33,33,50,50,50,50,50,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  RAICHU = {
    back = { image = "assets/battle/back-animated/gen3/raichu.png", width = 64, height = 64, columns = 16, frames = 30, durations = {50,50,33,33,50,50,50,50,50,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  SANDSHREW = {
    back = { image = "assets/battle/back-animated/gen3/sandshrew.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  SANDSLASH = {
    back = { image = "assets/battle/back-animated/gen3/sandslash.png", width = 81, height = 81, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  NIDORAN_F = {
    back = { image = "assets/battle/back-animated/gen3/nidoran-f.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  NIDORINA = {
    back = { image = "assets/battle/back-animated/gen3/nidorina.png", width = 74, height = 74, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  NIDOQUEEN = {
    back = { image = "assets/battle/back-animated/gen3/nidoqueen.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  NIDORAN_M = {
    back = { image = "assets/battle/back-animated/gen3/nidoran-m.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  NIDORINO = {
    back = { image = "assets/battle/back-animated/gen3/nidorino.png", width = 78, height = 78, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  NIDOKING = {
    back = { image = "assets/battle/back-animated/gen3/nidoking.png", width = 67, height = 67, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  CLEFAIRY = {
    back = { image = "assets/battle/back-animated/gen3/clefairy.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  CLEFABLE = {
    back = { image = "assets/battle/back-animated/gen3/clefable.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  VULPIX = {
    back = { image = "assets/battle/back-animated/gen3/vulpix.png", width = 74, height = 74, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  NINETALES = {
    back = { image = "assets/battle/back-animated/gen3/ninetales.png", width = 66, height = 66, columns = 16, frames = 39, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1067}, stableAnchor = true },
  },
  JIGGLYPUFF = {
    back = { image = "assets/battle/back-animated/gen3/jigglypuff.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  WIGGLYTUFF = {
    back = { image = "assets/battle/back-animated/gen3/wigglytuff.png", width = 64, height = 64, columns = 16, frames = 53, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,1050}, stableAnchor = true },
  },
  ZUBAT = {
    back = { image = "assets/battle/back-animated/gen3/zubat.png", width = 84, height = 84, columns = 16, frames = 73, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  GOLBAT = {
    back = { image = "assets/battle/back-animated/gen3/golbat.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  ODDISH = {
    back = { image = "assets/battle/back-animated/gen3/oddish.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  GLOOM = {
    back = { image = "assets/battle/back-animated/gen3/gloom.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  VILEPLUME = {
    back = { image = "assets/battle/back-animated/gen3/vileplume.png", width = 69, height = 69, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  PARAS = {
    back = { image = "assets/battle/back-animated/gen3/paras.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  PARASECT = {
    back = { image = "assets/battle/back-animated/gen3/parasect.png", width = 64, height = 64, columns = 16, frames = 38, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  VENONAT = {
    back = { image = "assets/battle/back-animated/gen3/venonat.png", width = 83, height = 83, columns = 16, frames = 43, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  VENOMOTH = {
    back = { image = "assets/battle/back-animated/gen3/venomoth.png", width = 86, height = 86, columns = 16, frames = 73, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  DIGLETT = {
    back = { image = "assets/battle/back-animated/gen3/diglett.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  DUGTRIO = {
    back = { image = "assets/battle/back-animated/gen3/dugtrio.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MEOWTH = {
    back = { image = "assets/battle/back-animated/gen3/meowth.png", width = 70, height = 70, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  PERSIAN = {
    back = { image = "assets/battle/back-animated/gen3/persian.png", width = 85, height = 85, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  PSYDUCK = {
    back = { image = "assets/battle/back-animated/gen3/psyduck.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  GOLDUCK = {
    back = { image = "assets/battle/back-animated/gen3/golduck.png", width = 66, height = 66, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MANKEY = {
    back = { image = "assets/battle/back-animated/gen3/mankey.png", width = 72, height = 72, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  PRIMEAPE = {
    back = { image = "assets/battle/back-animated/gen3/primeape.png", width = 75, height = 75, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  GROWLITHE = {
    back = { image = "assets/battle/back-animated/gen3/growlithe.png", width = 65, height = 65, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  ARCANINE = {
    back = { image = "assets/battle/back-animated/gen3/arcanine.png", width = 81, height = 81, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  POLIWAG = {
    back = { image = "assets/battle/back-animated/gen3/poliwag.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  POLIWHIRL = {
    back = { image = "assets/battle/back-animated/gen3/poliwhirl.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  POLIWRATH = {
    back = { image = "assets/battle/back-animated/gen3/poliwrath.png", width = 64, height = 64, columns = 16, frames = 36, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,67,385,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,50,1151}, stableAnchor = true },
  },
  ABRA = {
    back = { image = "assets/battle/back-animated/gen3/abra.png", width = 64, height = 64, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  KADABRA = {
    back = { image = "assets/battle/back-animated/gen3/kadabra.png", width = 64, height = 64, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  ALAKAZAM = {
    back = { image = "assets/battle/back-animated/gen3/alakazam.png", width = 73, height = 73, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MACHOP = {
    back = { image = "assets/battle/back-animated/gen3/machop.png", width = 65, height = 65, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  MACHOKE = {
    back = { image = "assets/battle/back-animated/gen3/machoke.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MACHAMP = {
    back = { image = "assets/battle/back-animated/gen3/machamp.png", width = 66, height = 66, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  BELLSPROUT = {
    back = { image = "assets/battle/back-animated/gen3/bellsprout.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  WEEPINBELL = {
    back = { image = "assets/battle/back-animated/gen3/weepinbell.png", width = 64, height = 64, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  VICTREEBEL = {
    back = { image = "assets/battle/back-animated/gen3/victreebel.png", width = 71, height = 71, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  TENTACOOL = {
    back = { image = "assets/battle/back-animated/gen3/tentacool.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  TENTACRUEL = {
    back = { image = "assets/battle/back-animated/gen3/tentacruel.png", width = 71, height = 71, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  GEODUDE = {
    back = { image = "assets/battle/back-animated/gen3/geodude.png", width = 64, height = 64, columns = 16, frames = 36, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,67,385,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,50,1151}, stableAnchor = true },
  },
  GRAVELER = {
    back = { image = "assets/battle/back-animated/gen3/graveler.png", width = 64, height = 64, columns = 16, frames = 38, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  GOLEM = {
    back = { image = "assets/battle/back-animated/gen3/golem.png", width = 67, height = 67, columns = 16, frames = 38, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  PONYTA = {
    back = { image = "assets/battle/back-animated/gen3/ponyta.png", width = 64, height = 64, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  RAPIDASH = {
    back = { image = "assets/battle/back-animated/gen3/rapidash.png", width = 80, height = 80, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  SLOWPOKE = {
    back = { image = "assets/battle/back-animated/gen3/slowpoke.png", width = 68, height = 68, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  SLOWBRO = {
    back = { image = "assets/battle/back-animated/gen3/slowbro.png", width = 67, height = 67, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  MAGNEMITE = {
    back = { image = "assets/battle/back-animated/gen3/magnemite.png", width = 64, height = 64, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MAGNETON = {
    back = { image = "assets/battle/back-animated/gen3/magneton.png", width = 72, height = 72, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  FARFETCHD = {
    back = { image = "assets/battle/back-animated/gen3/farfetchd.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  DODUO = {
    back = { image = "assets/battle/back-animated/gen3/doduo.png", width = 70, height = 70, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  DODRIO = {
    back = { image = "assets/battle/back-animated/gen3/dodrio.png", width = 81, height = 81, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  SEEL = {
    back = { image = "assets/battle/back-animated/gen3/seel.png", width = 65, height = 65, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  DEWGONG = {
    back = { image = "assets/battle/back-animated/gen3/dewgong.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  GRIMER = {
    back = { image = "assets/battle/back-animated/gen3/grimer.png", width = 64, height = 64, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MUK = {
    back = { image = "assets/battle/back-animated/gen3/muk.png", width = 92, height = 92, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  SHELLDER = {
    back = { image = "assets/battle/back-animated/gen3/shellder.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  CLOYSTER = {
    back = { image = "assets/battle/back-animated/gen3/cloyster.png", width = 81, height = 81, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  GASTLY = {
    back = { image = "assets/battle/back-animated/gen3/gastly.png", width = 81, height = 81, columns = 16, frames = 39, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1067}, stableAnchor = true },
  },
  HAUNTER = {
    back = { image = "assets/battle/back-animated/gen3/haunter.png", width = 68, height = 68, columns = 16, frames = 39, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1067}, stableAnchor = true },
  },
  GENGAR = {
    back = { image = "assets/battle/back-animated/gen3/gengar.png", width = 64, height = 64, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  ONIX = {
    back = { image = "assets/battle/back-animated/gen3/onix.png", width = 70, height = 70, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  DROWZEE = {
    back = { image = "assets/battle/back-animated/gen3/drowzee.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  HYPNO = {
    back = { image = "assets/battle/back-animated/gen3/hypno.png", width = 64, height = 64, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  KRABBY = {
    back = { image = "assets/battle/back-animated/gen3/krabby.png", width = 80, height = 80, columns = 16, frames = 43, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  KINGLER = {
    back = { image = "assets/battle/back-animated/gen3/kingler.png", width = 66, height = 66, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  VOLTORB = {
    back = { image = "assets/battle/back-animated/gen3/voltorb.png", width = 64, height = 64, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  ELECTRODE = {
    back = { image = "assets/battle/back-animated/gen3/electrode.png", width = 64, height = 64, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  EXEGGCUTE = {
    back = { image = "assets/battle/back-animated/gen3/exeggcute.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  EXEGGUTOR = {
    back = { image = "assets/battle/back-animated/gen3/exeggutor.png", width = 87, height = 87, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  CUBONE = {
    back = { image = "assets/battle/back-animated/gen3/cubone.png", width = 66, height = 66, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  MAROWAK = {
    back = { image = "assets/battle/back-animated/gen3/marowak.png", width = 68, height = 68, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  HITMONLEE = {
    back = { image = "assets/battle/back-animated/gen3/hitmonlee.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  HITMONCHAN = {
    back = { image = "assets/battle/back-animated/gen3/hitmonchan.png", width = 70, height = 70, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  LICKITUNG = {
    back = { image = "assets/battle/back-animated/gen3/lickitung.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  KOFFING = {
    back = { image = "assets/battle/back-animated/gen3/koffing.png", width = 64, height = 64, columns = 16, frames = 53, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,1050}, stableAnchor = true },
  },
  WEEZING = {
    back = { image = "assets/battle/back-animated/gen3/weezing.png", width = 71, height = 71, columns = 16, frames = 55, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,33,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,1050}, stableAnchor = true },
  },
  RHYHORN = {
    back = { image = "assets/battle/back-animated/gen3/rhyhorn.png", width = 64, height = 64, columns = 16, frames = 36, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,67,385,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,50,1151}, stableAnchor = true },
  },
  RHYDON = {
    back = { image = "assets/battle/back-animated/gen3/rhydon.png", width = 71, height = 71, columns = 16, frames = 36, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,67,385,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,50,1151}, stableAnchor = true },
  },
  CHANSEY = {
    back = { image = "assets/battle/back-animated/gen3/chansey.png", width = 66, height = 66, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  TANGELA = {
    back = { image = "assets/battle/back-animated/gen3/tangela.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  KANGASKHAN = {
    back = { image = "assets/battle/back-animated/gen3/kangaskhan.png", width = 65, height = 65, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  HORSEA = {
    back = { image = "assets/battle/back-animated/gen3/horsea.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  SEADRA = {
    back = { image = "assets/battle/back-animated/gen3/seadra.png", width = 78, height = 78, columns = 16, frames = 73, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  GOLDEEN = {
    back = { image = "assets/battle/back-animated/gen3/goldeen.png", width = 78, height = 78, columns = 16, frames = 73, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  SEAKING = {
    back = { image = "assets/battle/back-animated/gen3/seaking.png", width = 83, height = 83, columns = 16, frames = 73, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  STARYU = {
    back = { image = "assets/battle/back-animated/gen3/staryu.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  STARMIE = {
    back = { image = "assets/battle/back-animated/gen3/starmie.png", width = 70, height = 70, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  MR_MIME = {
    back = { image = "assets/battle/back-animated/gen3/mr-mime.png", width = 73, height = 73, columns = 16, frames = 41, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  SCYTHER = {
    back = { image = "assets/battle/back-animated/gen3/scyther.png", width = 76, height = 76, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  JYNX = {
    back = { image = "assets/battle/back-animated/gen3/jynx.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  ELECTABUZZ = {
    back = { image = "assets/battle/back-animated/gen3/electabuzz.png", width = 64, height = 64, columns = 16, frames = 30, durations = {50,50,33,33,50,50,50,50,50,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  MAGMAR = {
    back = { image = "assets/battle/back-animated/gen3/magmar.png", width = 64, height = 64, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  PINSIR = {
    back = { image = "assets/battle/back-animated/gen3/pinsir.png", width = 65, height = 65, columns = 16, frames = 36, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,67,385,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,50,1151}, stableAnchor = true },
  },
  TAUROS = {
    back = { image = "assets/battle/back-animated/gen3/tauros.png", width = 64, height = 64, columns = 16, frames = 36, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,67,385,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,50,1151}, stableAnchor = true },
  },
  MAGIKARP = {
    back = { image = "assets/battle/back-animated/gen3/magikarp.png", width = 75, height = 75, columns = 16, frames = 44, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  GYARADOS = {
    back = { image = "assets/battle/back-animated/gen3/gyarados.png", width = 70, height = 70, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  LAPRAS = {
    back = { image = "assets/battle/back-animated/gen3/lapras.png", width = 65, height = 65, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  DITTO = {
    back = { image = "assets/battle/back-animated/gen3/ditto.png", width = 64, height = 64, columns = 16, frames = 47, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  EEVEE = {
    back = { image = "assets/battle/back-animated/gen3/eevee.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  VAPOREON = {
    back = { image = "assets/battle/back-animated/gen3/vaporeon.png", width = 64, height = 64, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  JOLTEON = {
    back = { image = "assets/battle/back-animated/gen3/jolteon.png", width = 64, height = 64, columns = 16, frames = 30, durations = {50,50,33,33,50,50,50,50,50,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  FLAREON = {
    back = { image = "assets/battle/back-animated/gen3/flareon.png", width = 64, height = 64, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  PORYGON = {
    back = { image = "assets/battle/back-animated/gen3/porygon.png", width = 64, height = 64, columns = 16, frames = 39, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1067}, stableAnchor = true },
  },
  OMANYTE = {
    back = { image = "assets/battle/back-animated/gen3/omanyte.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  OMASTAR = {
    back = { image = "assets/battle/back-animated/gen3/omastar.png", width = 66, height = 66, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  KABUTO = {
    back = { image = "assets/battle/back-animated/gen3/kabuto.png", width = 64, height = 64, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  KABUTOPS = {
    back = { image = "assets/battle/back-animated/gen3/kabutops.png", width = 69, height = 69, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  AERODACTYL = {
    back = { image = "assets/battle/back-animated/gen3/aerodactyl.png", width = 79, height = 79, columns = 16, frames = 30, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  SNORLAX = {
    back = { image = "assets/battle/back-animated/gen3/snorlax.png", width = 67, height = 67, columns = 16, frames = 17, durations = {50,50,33,50,50,50,67,151,33,151,84,50,50,33,50,33,1084}, stableAnchor = true },
  },
  ARTICUNO = {
    back = { image = "assets/battle/back-animated/gen3/articuno.png", width = 64, height = 64, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  ZAPDOS = {
    back = { image = "assets/battle/back-animated/gen3/zapdos.png", width = 64, height = 64, columns = 16, frames = 30, durations = {50,50,33,33,50,50,50,50,50,50,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
  MOLTRES = {
    back = { image = "assets/battle/back-animated/gen3/moltres.png", width = 67, height = 67, columns = 16, frames = 40, durations = {67,67,67,33,67,67,67,67,100,100,100,117,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,134,100,100,100,67,67,67,67,33,67,67,1067}, stableAnchor = true },
  },
  DRATINI = {
    back = { image = "assets/battle/back-animated/gen3/dratini.png", width = 64, height = 64, columns = 16, frames = 29, durations = {33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,33,33,33,33,84,33,33,33,33,1050}, stableAnchor = true },
  },
  DRAGONAIR = {
    back = { image = "assets/battle/back-animated/gen3/dragonair.png", width = 76, height = 76, columns = 16, frames = 18, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  DRAGONITE = {
    back = { image = "assets/battle/back-animated/gen3/dragonite.png", width = 64, height = 64, columns = 16, frames = 37, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MEWTWO = {
    back = { image = "assets/battle/back-animated/gen3/mewtwo.png", width = 84, height = 84, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1050}, stableAnchor = true },
  },
  MEW = {
    back = { image = "assets/battle/back-animated/gen3/mew.png", width = 64, height = 64, columns = 16, frames = 31, durations = {33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,1033}, stableAnchor = true },
  },
}
