-- Generated by tools/import_animated_sprites.py --set gen3.
-- Pokemon Emerald animated fronts, National Dex #001-#151.
return {
  BULBASAUR = {
    front = { image = "assets/battle/front-animated/gen3/bulbasaur.png", width = 49, height = 45, columns = 16, frames = 29, durations = {80,20,40,20,20,20,20,20,20,20,80,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  IVYSAUR = {
    front = { image = "assets/battle/front-animated/gen3/ivysaur.png", width = 40, height = 54, columns = 16, frames = 21, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,2250} },
  },
  VENUSAUR = {
    front = { image = "assets/battle/front-animated/gen3/venusaur.png", width = 61, height = 72, columns = 16, frames = 27, durations = {80,20,20,20,20,220,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  CHARMANDER = {
    front = { image = "assets/battle/front-animated/gen3/charmander.png", width = 37, height = 47, columns = 16, frames = 17, durations = {80,20,20,40,20,20,20,40,20,20,20,20,20,20,20,140,2250} },
  },
  CHARMELEON = {
    front = { image = "assets/battle/front-animated/gen3/charmeleon.png", width = 74, height = 57, columns = 13, frames = 13, durations = {80,20,20,20,20,20,20,140,20,20,20,20,2250} },
  },
  CHARIZARD = {
    front = { image = "assets/battle/front-animated/gen3/charizard.png", width = 64, height = 68, columns = 16, frames = 21, durations = {80,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  SQUIRTLE = {
    front = { image = "assets/battle/front-animated/gen3/squirtle.png", width = 55, height = 40, columns = 16, frames = 42, durations = {80,20,20,20,20,20,20,20,20,20,20,120,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,120,20,20,20,20,20,20,20,20,20,2250} },
  },
  WARTORTLE = {
    front = { image = "assets/battle/front-animated/gen3/wartortle.png", width = 64, height = 53, columns = 16, frames = 25, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  BLASTOISE = {
    front = { image = "assets/battle/front-animated/gen3/blastoise.png", width = 64, height = 60, columns = 16, frames = 27, durations = {80,20,20,20,20,20,20,20,20,20,20,20,40,200,20,20,20,20,20,20,20,20,20,20,40,20,2250} },
  },
  CATERPIE = {
    front = { image = "assets/battle/front-animated/gen3/caterpie.png", width = 48, height = 35, columns = 16, frames = 49, durations = {80,40,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,60,20,20,20,20,20,20,20,20,20,20,40,2250} },
  },
  METAPOD = {
    front = { image = "assets/battle/front-animated/gen3/metapod.png", width = 63, height = 32, columns = 16, frames = 46, durations = {80,40,20,20,20,20,20,20,20,20,20,40,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,100,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  BUTTERFREE = {
    front = { image = "assets/battle/front-animated/gen3/butterfree.png", width = 76, height = 50, columns = 16, frames = 48, durations = {80,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,2250} },
  },
  WEEDLE = {
    front = { image = "assets/battle/front-animated/gen3/weedle.png", width = 45, height = 29, columns = 16, frames = 31, durations = {80,80,20,20,20,20,80,20,20,20,20,20,20,20,40,40,40,40,20,20,20,20,20,20,20,80,20,20,20,20,2250} },
  },
  KAKUNA = {
    front = { image = "assets/battle/front-animated/gen3/kakuna.png", width = 27, height = 38, columns = 16, frames = 27, durations = {80,60,40,60,20,20,20,20,20,20,20,40,20,40,60,40,60,40,20,40,20,20,20,20,20,20,2250} },
  },
  BEEDRILL = {
    front = { image = "assets/battle/front-animated/gen3/beedrill.png", width = 62, height = 48, columns = 14, frames = 14, durations = {80,320,20,20,40,20,160,20,20,20,20,20,40,2250} },
  },
  PIDGEY = {
    front = { image = "assets/battle/front-animated/gen3/pidgey.png", width = 43, height = 51, columns = 16, frames = 32, durations = {80,40,20,20,20,60,40,20,20,20,20,20,20,20,20,20,20,60,40,20,20,20,20,20,20,20,20,80,20,20,20,2250} },
  },
  PIDGEOTTO = {
    front = { image = "assets/battle/front-animated/gen3/pidgeotto.png", width = 49, height = 60, columns = 16, frames = 24, durations = {80,100,100,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  PIDGEOT = {
    front = { image = "assets/battle/front-animated/gen3/pidgeot.png", width = 88, height = 80, columns = 16, frames = 27, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  RATTATA = {
    front = { image = "assets/battle/front-animated/gen3/rattata.png", width = 61, height = 34, columns = 16, frames = 44, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  RATICATE = {
    front = { image = "assets/battle/front-animated/gen3/raticate.png", width = 82, height = 65, columns = 16, frames = 35, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  SPEAROW = {
    front = { image = "assets/battle/front-animated/gen3/spearow.png", width = 38, height = 45, columns = 16, frames = 48, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,60,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  FEAROW = {
    front = { image = "assets/battle/front-animated/gen3/fearow.png", width = 90, height = 74, columns = 16, frames = 35, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  EKANS = {
    front = { image = "assets/battle/front-animated/gen3/ekans.png", width = 68, height = 42, columns = 16, frames = 26, durations = {80,80,80,80,80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  ARBOK = {
    front = { image = "assets/battle/front-animated/gen3/arbok.png", width = 57, height = 75, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  PIKACHU = {
    front = { image = "assets/battle/front-animated/gen3/pikachu.png", width = 45, height = 52, columns = 16, frames = 16, durations = {80,20,60,100,60,20,20,20,20,40,20,40,20,40,160,2250} },
  },
  RAICHU = {
    front = { image = "assets/battle/front-animated/gen3/raichu.png", width = 52, height = 71, columns = 16, frames = 24, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,80,200,2250} },
  },
  SANDSHREW = {
    front = { image = "assets/battle/front-animated/gen3/sandshrew.png", width = 56, height = 39, columns = 16, frames = 23, durations = {80,20,20,20,20,60,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,2250} },
  },
  SANDSLASH = {
    front = { image = "assets/battle/front-animated/gen3/sandslash.png", width = 50, height = 57, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  NIDORAN_F = {
    front = { image = "assets/battle/front-animated/gen3/nidoran-f.png", width = 33, height = 47, columns = 16, frames = 29, durations = {80,60,40,60,80,20,20,20,40,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,40,40,2250} },
  },
  NIDORINA = {
    front = { image = "assets/battle/front-animated/gen3/nidorina.png", width = 51, height = 49, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  NIDOQUEEN = {
    front = { image = "assets/battle/front-animated/gen3/nidoqueen.png", width = 67, height = 58, columns = 16, frames = 21, durations = {80,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,40,2250} },
  },
  NIDORAN_M = {
    front = { image = "assets/battle/front-animated/gen3/nidoran-m.png", width = 44, height = 57, columns = 16, frames = 21, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  NIDORINO = {
    front = { image = "assets/battle/front-animated/gen3/nidorino.png", width = 61, height = 57, columns = 16, frames = 25, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  NIDOKING = {
    front = { image = "assets/battle/front-animated/gen3/nidoking.png", width = 62, height = 60, columns = 16, frames = 22, durations = {80,100,140,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  CLEFAIRY = {
    front = { image = "assets/battle/front-animated/gen3/clefairy.png", width = 41, height = 50, columns = 16, frames = 26, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  CLEFABLE = {
    front = { image = "assets/battle/front-animated/gen3/clefable.png", width = 63, height = 59, columns = 16, frames = 85, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,2250} },
  },
  VULPIX = {
    front = { image = "assets/battle/front-animated/gen3/vulpix.png", width = 56, height = 50, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,100,200,2250} },
  },
  NINETALES = {
    front = { image = "assets/battle/front-animated/gen3/ninetales.png", width = 61, height = 68, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,100,200,2250} },
  },
  JIGGLYPUFF = {
    front = { image = "assets/battle/front-animated/gen3/jigglypuff.png", width = 51, height = 45, columns = 16, frames = 45, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  WIGGLYTUFF = {
    front = { image = "assets/battle/front-animated/gen3/wigglytuff.png", width = 68, height = 61, columns = 16, frames = 25, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,60,200,2250} },
  },
  ZUBAT = {
    front = { image = "assets/battle/front-animated/gen3/zubat.png", width = 52, height = 70, columns = 16, frames = 24, durations = {80,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  GOLBAT = {
    front = { image = "assets/battle/front-animated/gen3/golbat.png", width = 83, height = 66, columns = 16, frames = 50, durations = {80,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  ODDISH = {
    front = { image = "assets/battle/front-animated/gen3/oddish.png", width = 35, height = 48, columns = 16, frames = 28, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,120,2250} },
  },
  GLOOM = {
    front = { image = "assets/battle/front-animated/gen3/gloom.png", width = 51, height = 58, columns = 16, frames = 49, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  VILEPLUME = {
    front = { image = "assets/battle/front-animated/gen3/vileplume.png", width = 74, height = 65, columns = 16, frames = 84, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,2250} },
  },
  PARAS = {
    front = { image = "assets/battle/front-animated/gen3/paras.png", width = 52, height = 37, columns = 16, frames = 36, durations = {80,60,40,20,20,20,20,20,100,20,20,20,20,20,20,20,20,100,20,20,20,20,20,20,20,20,40,60,20,20,20,20,60,40,60,2250} },
  },
  PARASECT = {
    front = { image = "assets/battle/front-animated/gen3/parasect.png", width = 67, height = 53, columns = 16, frames = 24, durations = {80,100,100,100,140,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  VENONAT = {
    front = { image = "assets/battle/front-animated/gen3/venonat.png", width = 54, height = 60, columns = 16, frames = 32, durations = {80,40,60,40,60,20,20,40,20,20,20,40,20,100,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  VENOMOTH = {
    front = { image = "assets/battle/front-animated/gen3/venomoth.png", width = 72, height = 70, columns = 16, frames = 55, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DIGLETT = {
    front = { image = "assets/battle/front-animated/gen3/diglett.png", width = 42, height = 43, columns = 16, frames = 20, durations = {80,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DUGTRIO = {
    front = { image = "assets/battle/front-animated/gen3/dugtrio.png", width = 54, height = 40, columns = 16, frames = 42, durations = {80,340,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  MEOWTH = {
    front = { image = "assets/battle/front-animated/gen3/meowth.png", width = 39, height = 47, columns = 16, frames = 20, durations = {80,80,80,80,160,20,20,40,20,20,20,40,20,20,20,20,20,20,20,2250} },
  },
  PERSIAN = {
    front = { image = "assets/battle/front-animated/gen3/persian.png", width = 57, height = 61, columns = 16, frames = 22, durations = {80,220,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  PSYDUCK = {
    front = { image = "assets/battle/front-animated/gen3/psyduck.png", width = 53, height = 56, columns = 16, frames = 28, durations = {80,20,20,40,20,20,20,40,20,120,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,2250} },
  },
  GOLDUCK = {
    front = { image = "assets/battle/front-animated/gen3/golduck.png", width = 62, height = 61, columns = 16, frames = 36, durations = {80,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,40,20,20,20,20,2250} },
  },
  MANKEY = {
    front = { image = "assets/battle/front-animated/gen3/mankey.png", width = 67, height = 75, columns = 16, frames = 42, durations = {80,60,40,60,60,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  PRIMEAPE = {
    front = { image = "assets/battle/front-animated/gen3/primeape.png", width = 67, height = 63, columns = 16, frames = 45, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  GROWLITHE = {
    front = { image = "assets/battle/front-animated/gen3/growlithe.png", width = 60, height = 43, columns = 16, frames = 16, durations = {80,80,80,80,60,20,20,20,20,20,20,140,20,20,20,2250} },
  },
  ARCANINE = {
    front = { image = "assets/battle/front-animated/gen3/arcanine.png", width = 69, height = 59, columns = 16, frames = 16, durations = {80,80,80,80,140,40,20,20,40,20,160,20,40,20,20,2250} },
  },
  POLIWAG = {
    front = { image = "assets/battle/front-animated/gen3/poliwag.png", width = 56, height = 48, columns = 16, frames = 26, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  POLIWHIRL = {
    front = { image = "assets/battle/front-animated/gen3/poliwhirl.png", width = 89, height = 73, columns = 16, frames = 38, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  POLIWRATH = {
    front = { image = "assets/battle/front-animated/gen3/poliwrath.png", width = 57, height = 56, columns = 16, frames = 26, durations = {80,20,20,40,20,20,40,20,20,40,20,20,180,20,20,20,20,40,20,20,20,20,20,20,40,2250} },
  },
  ABRA = {
    front = { image = "assets/battle/front-animated/gen3/abra.png", width = 58, height = 47, columns = 16, frames = 24, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,180,2250} },
  },
  KADABRA = {
    front = { image = "assets/battle/front-animated/gen3/kadabra.png", width = 54, height = 65, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,160,2250} },
  },
  ALAKAZAM = {
    front = { image = "assets/battle/front-animated/gen3/alakazam.png", width = 59, height = 66, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,220,2250} },
  },
  MACHOP = {
    front = { image = "assets/battle/front-animated/gen3/machop.png", width = 39, height = 56, columns = 16, frames = 26, durations = {80,20,20,20,40,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,100,160,140,2250} },
  },
  MACHOKE = {
    front = { image = "assets/battle/front-animated/gen3/machoke.png", width = 46, height = 57, columns = 16, frames = 21, durations = {80,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,240,2250} },
  },
  MACHAMP = {
    front = { image = "assets/battle/front-animated/gen3/machamp.png", width = 78, height = 68, columns = 16, frames = 25, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,120,100,2250} },
  },
  BELLSPROUT = {
    front = { image = "assets/battle/front-animated/gen3/bellsprout.png", width = 46, height = 55, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  WEEPINBELL = {
    front = { image = "assets/battle/front-animated/gen3/weepinbell.png", width = 77, height = 47, columns = 16, frames = 43, durations = {80,20,20,20,20,20,20,20,20,20,80,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,100,20,20,20,20,20,20,20,20,20,2250} },
  },
  VICTREEBEL = {
    front = { image = "assets/battle/front-animated/gen3/victreebel.png", width = 84, height = 75, columns = 16, frames = 38, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  TENTACOOL = {
    front = { image = "assets/battle/front-animated/gen3/tentacool.png", width = 37, height = 64, columns = 16, frames = 26, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  TENTACRUEL = {
    front = { image = "assets/battle/front-animated/gen3/tentacruel.png", width = 71, height = 75, columns = 16, frames = 29, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,180,200,2250} },
  },
  GEODUDE = {
    front = { image = "assets/battle/front-animated/gen3/geodude.png", width = 56, height = 51, columns = 16, frames = 44, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  GRAVELER = {
    front = { image = "assets/battle/front-animated/gen3/graveler.png", width = 86, height = 72, columns = 16, frames = 45, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  GOLEM = {
    front = { image = "assets/battle/front-animated/gen3/golem.png", width = 60, height = 71, columns = 16, frames = 26, durations = {80,20,20,20,220,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  PONYTA = {
    front = { image = "assets/battle/front-animated/gen3/ponyta.png", width = 54, height = 50, columns = 16, frames = 26, durations = {80,20,20,20,20,20,20,20,20,20,40,20,80,20,80,20,40,20,20,20,20,20,20,20,20,2250} },
  },
  RAPIDASH = {
    front = { image = "assets/battle/front-animated/gen3/rapidash.png", width = 76, height = 72, columns = 16, frames = 27, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  SLOWPOKE = {
    front = { image = "assets/battle/front-animated/gen3/slowpoke.png", width = 54, height = 48, columns = 16, frames = 47, durations = {80,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,2250} },
  },
  SLOWBRO = {
    front = { image = "assets/battle/front-animated/gen3/slowbro.png", width = 78, height = 56, columns = 16, frames = 42, durations = {80,20,20,20,20,20,20,20,20,20,20,120,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,120,20,20,20,20,20,20,20,20,20,2250} },
  },
  MAGNEMITE = {
    front = { image = "assets/battle/front-animated/gen3/magnemite.png", width = 51, height = 56, columns = 16, frames = 67, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,100,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  MAGNETON = {
    front = { image = "assets/battle/front-animated/gen3/magneton.png", width = 49, height = 48, columns = 16, frames = 18, durations = {80,20,60,100,40,20,20,40,20,40,20,40,20,40,20,140,140,2250} },
  },
  FARFETCHD = {
    front = { image = "assets/battle/front-animated/gen3/farfetchd.png", width = 70, height = 59, columns = 16, frames = 46, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DODUO = {
    front = { image = "assets/battle/front-animated/gen3/doduo.png", width = 51, height = 53, columns = 16, frames = 38, durations = {80,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DODRIO = {
    front = { image = "assets/battle/front-animated/gen3/dodrio.png", width = 89, height = 83, columns = 16, frames = 37, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,60,120,120,2250} },
  },
  SEEL = {
    front = { image = "assets/battle/front-animated/gen3/seel.png", width = 75, height = 51, columns = 16, frames = 45, durations = {80,20,20,20,20,20,20,20,20,20,20,100,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,80,20,20,20,20,20,20,20,20,20,40,2250} },
  },
  DEWGONG = {
    front = { image = "assets/battle/front-animated/gen3/dewgong.png", width = 73, height = 76, columns = 16, frames = 49, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  GRIMER = {
    front = { image = "assets/battle/front-animated/gen3/grimer.png", width = 61, height = 43, columns = 16, frames = 30, durations = {80,20,20,20,20,100,20,20,20,20,20,20,20,20,40,60,20,20,20,20,20,20,20,20,100,20,20,20,20,2250} },
  },
  MUK = {
    front = { image = "assets/battle/front-animated/gen3/muk.png", width = 71, height = 67, columns = 16, frames = 37, durations = {80,100,100,100,60,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  SHELLDER = {
    front = { image = "assets/battle/front-animated/gen3/shellder.png", width = 35, height = 35, columns = 16, frames = 21, durations = {80,60,40,120,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,2250} },
  },
  CLOYSTER = {
    front = { image = "assets/battle/front-animated/gen3/cloyster.png", width = 77, height = 58, columns = 16, frames = 50, durations = {80,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  GASTLY = {
    front = { image = "assets/battle/front-animated/gen3/gastly.png", width = 54, height = 55, columns = 16, frames = 32, durations = {80,40,40,20,20,20,40,20,40,20,40,20,40,40,60,60,280,60,60,40,40,20,40,20,40,20,40,20,20,20,40,2250} },
  },
  HAUNTER = {
    front = { image = "assets/battle/front-animated/gen3/haunter.png", width = 64, height = 56, columns = 13, frames = 13, durations = {80,80,160,40,20,20,20,160,20,60,20,280,2250} },
  },
  GENGAR = {
    front = { image = "assets/battle/front-animated/gen3/gengar.png", width = 77, height = 69, columns = 16, frames = 46, durations = {80,20,20,20,20,20,40,20,20,20,40,20,40,20,20,20,20,20,20,40,20,20,20,40,60,20,20,20,20,40,100,40,20,20,20,20,20,20,20,20,20,20,20,20,40,2250} },
  },
  ONIX = {
    front = { image = "assets/battle/front-animated/gen3/onix.png", width = 81, height = 63, columns = 16, frames = 45, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DROWZEE = {
    front = { image = "assets/battle/front-animated/gen3/drowzee.png", width = 67, height = 55, columns = 16, frames = 28, durations = {80,120,120,120,120,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  HYPNO = {
    front = { image = "assets/battle/front-animated/gen3/hypno.png", width = 55, height = 57, columns = 9, frames = 9, durations = {80,160,100,40,160,140,60,100,2250} },
  },
  KRABBY = {
    front = { image = "assets/battle/front-animated/gen3/krabby.png", width = 60, height = 42, columns = 16, frames = 19, durations = {80,20,20,20,20,40,20,20,20,20,40,20,20,20,20,60,20,20,2250} },
  },
  KINGLER = {
    front = { image = "assets/battle/front-animated/gen3/kingler.png", width = 76, height = 74, columns = 16, frames = 55, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  VOLTORB = {
    front = { image = "assets/battle/front-animated/gen3/voltorb.png", width = 29, height = 40, columns = 16, frames = 27, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,80,2250} },
  },
  ELECTRODE = {
    front = { image = "assets/battle/front-animated/gen3/electrode.png", width = 41, height = 50, columns = 16, frames = 27, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,260,2250} },
  },
  EXEGGCUTE = {
    front = { image = "assets/battle/front-animated/gen3/exeggcute.png", width = 70, height = 52, columns = 16, frames = 31, durations = {80,20,20,20,20,100,20,20,20,20,20,20,20,20,40,60,20,20,20,20,20,20,20,20,80,20,20,20,20,20,2250} },
  },
  EXEGGUTOR = {
    front = { image = "assets/battle/front-animated/gen3/exeggutor.png", width = 80, height = 74, columns = 16, frames = 39, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  CUBONE = {
    front = { image = "assets/battle/front-animated/gen3/cubone.png", width = 55, height = 54, columns = 16, frames = 46, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  MAROWAK = {
    front = { image = "assets/battle/front-animated/gen3/marowak.png", width = 67, height = 71, columns = 16, frames = 46, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  HITMONLEE = {
    front = { image = "assets/battle/front-animated/gen3/hitmonlee.png", width = 75, height = 59, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  HITMONCHAN = {
    front = { image = "assets/battle/front-animated/gen3/hitmonchan.png", width = 45, height = 57, columns = 10, frames = 10, durations = {80,60,40,60,40,60,140,60,200,2250} },
  },
  LICKITUNG = {
    front = { image = "assets/battle/front-animated/gen3/lickitung.png", width = 65, height = 70, columns = 16, frames = 47, durations = {80,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,2250} },
  },
  KOFFING = {
    front = { image = "assets/battle/front-animated/gen3/koffing.png", width = 62, height = 55, columns = 16, frames = 24, durations = {80,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  WEEZING = {
    front = { image = "assets/battle/front-animated/gen3/weezing.png", width = 64, height = 72, columns = 16, frames = 18, durations = {80,20,20,40,20,20,20,20,20,40,20,20,20,20,60,20,20,2250} },
  },
  RHYHORN = {
    front = { image = "assets/battle/front-animated/gen3/rhyhorn.png", width = 55, height = 51, columns = 16, frames = 19, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  RHYDON = {
    front = { image = "assets/battle/front-animated/gen3/rhydon.png", width = 73, height = 69, columns = 16, frames = 24, durations = {80,20,20,20,40,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,300,2250} },
  },
  CHANSEY = {
    front = { image = "assets/battle/front-animated/gen3/chansey.png", width = 60, height = 63, columns = 16, frames = 47, durations = {80,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,2250} },
  },
  TANGELA = {
    front = { image = "assets/battle/front-animated/gen3/tangela.png", width = 65, height = 64, columns = 16, frames = 46, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  KANGASKHAN = {
    front = { image = "assets/battle/front-animated/gen3/kangaskhan.png", width = 63, height = 75, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  HORSEA = {
    front = { image = "assets/battle/front-animated/gen3/horsea.png", width = 37, height = 39, columns = 16, frames = 16, durations = {80,20,40,20,20,40,20,20,20,20,20,20,40,20,180,2250} },
  },
  SEADRA = {
    front = { image = "assets/battle/front-animated/gen3/seadra.png", width = 55, height = 63, columns = 16, frames = 19, durations = {80,20,20,60,20,20,20,20,20,20,20,20,20,20,60,20,20,100,2250} },
  },
  GOLDEEN = {
    front = { image = "assets/battle/front-animated/gen3/goldeen.png", width = 72, height = 49, columns = 16, frames = 49, durations = {80,20,20,20,20,20,20,20,20,20,20,40,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,80,20,20,20,20,20,20,20,20,20,20,20,100,160,2250} },
  },
  SEAKING = {
    front = { image = "assets/battle/front-animated/gen3/seaking.png", width = 58, height = 77, columns = 16, frames = 51, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  STARYU = {
    front = { image = "assets/battle/front-animated/gen3/staryu.png", width = 47, height = 47, columns = 16, frames = 58, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,120,20,40,20,20,40,20,20,40,20,20,40,20,20,40,20,20,40,20,20,40,20,20,40,20,2250} },
  },
  STARMIE = {
    front = { image = "assets/battle/front-animated/gen3/starmie.png", width = 56, height = 55, columns = 16, frames = 16, durations = {80,20,40,20,20,40,20,20,20,20,20,20,40,20,180,2250} },
  },
  MR_MIME = {
    front = { image = "assets/battle/front-animated/gen3/mr-mime.png", width = 59, height = 48, columns = 16, frames = 29, durations = {80,40,20,20,20,60,40,20,20,20,20,20,20,20,40,80,40,20,20,20,20,20,20,20,100,20,20,20,2250} },
  },
  SCYTHER = {
    front = { image = "assets/battle/front-animated/gen3/scyther.png", width = 65, height = 64, columns = 16, frames = 19, durations = {80,60,40,40,20,20,20,40,60,20,40,20,20,20,20,20,40,60,2250} },
  },
  JYNX = {
    front = { image = "assets/battle/front-animated/gen3/jynx.png", width = 56, height = 70, columns = 16, frames = 24, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,100,700,2250} },
  },
  ELECTABUZZ = {
    front = { image = "assets/battle/front-animated/gen3/electabuzz.png", width = 61, height = 58, columns = 16, frames = 16, durations = {80,80,20,100,60,40,40,20,40,20,40,20,40,20,60,2250} },
  },
  MAGMAR = {
    front = { image = "assets/battle/front-animated/gen3/magmar.png", width = 63, height = 63, columns = 16, frames = 20, durations = {80,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  PINSIR = {
    front = { image = "assets/battle/front-animated/gen3/pinsir.png", width = 68, height = 67, columns = 16, frames = 21, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  TAUROS = {
    front = { image = "assets/battle/front-animated/gen3/tauros.png", width = 58, height = 73, columns = 16, frames = 27, durations = {80,100,20,40,20,20,40,20,20,20,20,20,20,180,20,20,20,20,40,20,20,20,20,20,20,40,2250} },
  },
  MAGIKARP = {
    front = { image = "assets/battle/front-animated/gen3/magikarp.png", width = 67, height = 62, columns = 16, frames = 44, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  GYARADOS = {
    front = { image = "assets/battle/front-animated/gen3/gyarados.png", width = 82, height = 69, columns = 16, frames = 44, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  LAPRAS = {
    front = { image = "assets/battle/front-animated/gen3/lapras.png", width = 64, height = 55, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DITTO = {
    front = { image = "assets/battle/front-animated/gen3/ditto.png", width = 40, height = 35, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  EEVEE = {
    front = { image = "assets/battle/front-animated/gen3/eevee.png", width = 38, height = 51, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  VAPOREON = {
    front = { image = "assets/battle/front-animated/gen3/vaporeon.png", width = 46, height = 59, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  JOLTEON = {
    front = { image = "assets/battle/front-animated/gen3/jolteon.png", width = 60, height = 62, columns = 16, frames = 24, durations = {80,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  FLAREON = {
    front = { image = "assets/battle/front-animated/gen3/flareon.png", width = 43, height = 58, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  PORYGON = {
    front = { image = "assets/battle/front-animated/gen3/porygon.png", width = 47, height = 46, columns = 16, frames = 16, durations = {80,20,20,40,20,20,20,20,20,20,20,20,20,40,20,2250} },
  },
  OMANYTE = {
    front = { image = "assets/battle/front-animated/gen3/omanyte.png", width = 36, height = 47, columns = 16, frames = 49, durations = {80,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,2250} },
  },
  OMASTAR = {
    front = { image = "assets/battle/front-animated/gen3/omastar.png", width = 63, height = 58, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  KABUTO = {
    front = { image = "assets/battle/front-animated/gen3/kabuto.png", width = 51, height = 35, columns = 16, frames = 49, durations = {80,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,2250} },
  },
  KABUTOPS = {
    front = { image = "assets/battle/front-animated/gen3/kabutops.png", width = 66, height = 57, columns = 16, frames = 20, durations = {80,40,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  AERODACTYL = {
    front = { image = "assets/battle/front-animated/gen3/aerodactyl.png", width = 64, height = 72, columns = 16, frames = 31, durations = {80,20,20,20,20,20,100,20,20,20,20,20,20,20,20,80,20,20,20,20,20,20,20,20,20,100,20,20,20,20,2250} },
  },
  SNORLAX = {
    front = { image = "assets/battle/front-animated/gen3/snorlax.png", width = 80, height = 58, columns = 16, frames = 42, durations = {80,20,20,20,20,20,20,20,20,20,20,120,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,120,20,20,20,20,20,20,20,20,20,2250} },
  },
  ARTICUNO = {
    front = { image = "assets/battle/front-animated/gen3/articuno.png", width = 73, height = 68, columns = 16, frames = 23, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,200,2250} },
  },
  ZAPDOS = {
    front = { image = "assets/battle/front-animated/gen3/zapdos.png", width = 64, height = 59, columns = 16, frames = 16, durations = {80,80,20,100,60,40,40,20,40,20,40,20,20,20,20,2250} },
  },
  MOLTRES = {
    front = { image = "assets/battle/front-animated/gen3/moltres.png", width = 72, height = 68, columns = 16, frames = 50, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DRATINI = {
    front = { image = "assets/battle/front-animated/gen3/dratini.png", width = 60, height = 54, columns = 16, frames = 23, durations = {80,20,20,20,40,20,20,20,20,20,20,40,20,20,20,20,20,20,40,20,20,20,2250} },
  },
  DRAGONAIR = {
    front = { image = "assets/battle/front-animated/gen3/dragonair.png", width = 62, height = 60, columns = 16, frames = 21, durations = {80,20,20,20,20,20,20,20,20,40,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  DRAGONITE = {
    front = { image = "assets/battle/front-animated/gen3/dragonite.png", width = 64, height = 72, columns = 16, frames = 28, durations = {80,40,20,20,20,100,20,20,20,20,20,20,20,40,80,40,20,20,20,20,20,20,20,100,20,20,20,2250} },
  },
  MEWTWO = {
    front = { image = "assets/battle/front-animated/gen3/mewtwo.png", width = 65, height = 72, columns = 16, frames = 22, durations = {80,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,2250} },
  },
  MEW = {
    front = { image = "assets/battle/front-animated/gen3/mew.png", width = 66, height = 41, columns = 16, frames = 47, durations = {80,20,20,20,20,20,20,20,20,20,20,20,40,20,40,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,100,20,20,20,20,20,20,20,20,20,20,2250} },
  },
}
