"""Import Kanto Emerald animated and static back-sprite collections.

`Spr b 3e` APNGs are flattened into native-resolution atlases for LÖVE.
`Spr b 3r` single-frame PNGs are copied byte-for-byte so their indexed pixels
and source transparency remain untouched.
"""

from __future__ import annotations

import argparse
import urllib.parse
from io import BytesIO
from pathlib import Path

from PIL import Image

from import_animated_sprites import convert, download, lua_definition, species


SOURCE = "https://archives.bulbagarden.net/wiki/Special:Redirect/file"


def archive_png(base: str, filename: str) -> bytes:
    url = f"{base.rstrip('/')}/{urllib.parse.quote(filename)}"
    raw = download(url)
    if not raw.startswith(b"\x89PNG\r\n\x1a\n"):
        raise ValueError(f"{filename}: response is not a PNG")
    return raw


def validate_static(raw: bytes, filename: str) -> tuple[int, int, str]:
    with Image.open(BytesIO(raw)) as image:
        if getattr(image, "n_frames", 1) != 1:
            raise ValueError(f"{filename}: expected one static frame")
        width, height, mode = image.width, image.height, image.mode
        image.verify()
    return width, height, mode


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--base-url", default=SOURCE)
    args = parser.parse_args()

    root = args.root.resolve()
    records = []
    roster = species(root)
    for number, (engine_name, slug) in enumerate(roster, 1):
        animated_name = f"Spr b 3e {number:03d}.png"
        animated = archive_png(args.base_url, animated_name)
        animated_rel = f"assets/battle/back-animated/gen3/{slug}.png"
        # The archive APNGs frequently encode holds as repeated cells and use
        # one-tick (~16 ms) poses. Merge only consecutive visual duplicates,
        # retaining their combined time, then keep every remaining pose on
        # screen for at least two 60 Hz updates so it is visible in LÖVE.
        info = convert(
            animated,
            root / animated_rel,
            coalesce=True,
            minimum_duration=33,
        )

        static_name = f"Spr b 3r {number:03d}.png"
        static_path = root / "assets" / "battle" / "back-static" / "gen3" / f"{slug}.png"
        # A complete import needs animated timing metadata, so APNGs are read
        # on every run. Static files carry no sidecar state and can be resumed
        # safely after a slow archive or an interrupted command.
        static = (static_path.read_bytes() if static_path.exists()
                  else archive_png(args.base_url, static_name))
        width, height, mode = validate_static(static, static_name)
        static_path.parent.mkdir(parents=True, exist_ok=True)
        static_path.write_bytes(static)

        records.append((engine_name, animated_rel, info))
        print(
            f"[{number:03d}/151] {slug:<12s} "
            f"animated={info['frames']}x{info['width']}x{info['height']} "
            f"static={width}x{height} {mode}",
            flush=True,
        )

    lines = [
        "-- Generated by tools/import_emerald_back_sprites.py.",
        "-- Pokemon Emerald animated backs, National Dex #001-#151.",
        "return {",
    ]
    for engine_name, path, info in records:
        lines.append(f"  {engine_name} = {{")
        lines.append(
            f"    back = {lua_definition(path, info, stable_anchor=True)},"
        )
        lines.append("  },")
    lines.append("}")
    metadata = root / "data" / "animated_battle_backs_gen3.lua"
    metadata.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {metadata} with {len(records)} species")


if __name__ == "__main__":
    main()
